name: sweepy

services:
  sweepy:
    container_name: sweepy
    image: ghcr.io/casscassca/sweepy:latest
    build: .
    env_file:
      - path: .env
        required: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${SWEEPY_PORT:-3000}:3000"
    volumes:
      - sweepy-data:/app/data
    environment:
      TZ: ${TZ:-America/Chicago}
    restart: unless-stopped

volumes:
  sweepy-data:
