-- AlterTable
ALTER TABLE "Task" ADD COLUMN "addonName" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Task" ADD COLUMN "addonFrequencyDays" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Task" ADD COLUMN "addonPoints" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "Task" ADD COLUMN "addonLastDoneAt" DATETIME;
